name: quiz_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  connectivity_plus: ^2.3.0
  google_fonts: ^2.3.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  pin_code_text_field: ^1.8.0
  device_info_plus: ^3.2.4
  dio: ^4.0.6
  equatable: ^2.0.3
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  logger: ^1.1.0
  mockito: ^5.1.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - data/
